language: php

php:
   - 7.1
   - 7.2
   - 7.3
   - 7.4

env:
   - ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=~7.0 TESTBENCH_VERSION=3.6
   - ILLUMINATE_VERSION=5.7.* PHPUNIT_VERSION=~7.0 TESTBENCH_VERSION=3.7
   - ILLUMINATE_VERSION=5.8.* PHPUNIT_VERSION=~7.0 TESTBENCH_VERSION=3.8
   - ILLUMINATE_VERSION=^6.0 PHPUNIT_VERSION=~8.0 TESTBENCH_VERSION=^4.0
   - ILLUMINATE_VERSION=^7.0 PHPUNIT_VERSION=~8.0 TESTBENCH_VERSION=^5.0

matrix:
   fast_finish: true
   exclude:
      - php: 7.1
        env: ILLUMINATE_VERSION=^6.0 PHPUNIT_VERSION=~8.0 TESTBENCH_VERSION=^4.0
      - php: 7.1
        env: ILLUMINATE_VERSION=^7.0 PHPUNIT_VERSION=~8.0 TESTBENCH_VERSION=^5.0

before_install:
   - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update --prefer-dist
   - composer require "illuminate/contracts:${ILLUMINATE_VERSION}" --no-update --prefer-dist
   - composer require "illuminate/view:${ILLUMINATE_VERSION}" --no-update --prefer-dist
   - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --prefer-dist
   - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update --prefer-dist

install: travis_retry composer install --no-interaction --prefer-dist

script:
   - vendor/bin/phpunit

